server:
  port: 8081
spring:
  application:
    name: wishlist
  data:
    mongodb:
      host: localhost
      port: 27017
      database: wishlist
      # username: ${MONGODB_USERNAME:}
      # password: ${MONGODB_PASSWORD:}
      # authentication-database: admin
      # uri: mongodb://localhost:27017/wishlist
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
wishlist:
  validation:
    max-products-per-wishlist: 10
  repository:
    type: mongodb